on:
  push:
    branches: [ FinalProjectCorrection ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout on master
          uses: actions/checkout@master

        - name: Initialize Composer
          uses: php-actions/composer@v5
          with: 
            working_dir: ./Back

        - name: Run phpunit tests  
          uses: php-actions/phpunit@v3
          with: 
            working-directory: ./Back

        - name: Run cypress tests 
          uses: cypress-io/github-action@v2
          with:
            working-directory: ./Front
            start: |
              npm start
            wait-on: 'http://localhost:3000'
            config: baseUrl=https://localhost:3000

        - name: Run react tests
          working-directory: ./Front
          run: |
            npm ci
            npm run build --if-present
            npm test 
